<?php

declare(strict_types=1);

namespace KazSign\Controllers;

use KazSign\Core\Controller;
use KazSign\Core\Database;
use KazSign\Core\KazSignEngine;

/**
 * CredentialController
 *
 * issue()  — Issuer creates and signs a credential (POST /credentials/issue)
 * revoke() — Issuer revokes a credential          (POST /credentials/revoke)
 * verify() — Verifier checks a credential         (POST /credentials/verify)
 * show()   — View a single credential as JSON-LD  (GET  /credentials/:id/show)
 *
 * ── CERTIFICATE SERIAL NUMBER ────────────────────────────────────────────────
 * Every issued credential is assigned a numeric serial number at issuance
 * time. This is the identifier printed on the PDF certificate and is what
 * Verifiers use to look up a credential — replacing the old urn:uuid lookup.
 *
 *   Format : a random 8-digit number
 *   Example: 88903405
 *
 * The internal `credential_id` (urn:uuid:...) is still generated and stored as
 * the W3C VC Data Model `id` (a globally unique URI), but it is no longer the
 * lookup key exposed to verifiers.
 */
final class CredentialController extends Controller
{
    // =========================================================================
    //  POST /credentials/issue
    // =========================================================================

    public function issue(array $params = []): void
    {
        $this->requireAuth();
        $this->requireRole('issuer');
        $this->validateCsrf();

        $holderId       = (int)  ($_POST['holder_id']      ?? 0);
        $credentialType = trim(   $_POST['credential_type'] ?? 'AcademicCredential');
        $subjectData    = trim(   $_POST['subject_data']    ?? '');

        if ($holderId === 0 || $subjectData === '') {
            $this->flashAndRedirect('error', 'Holder and subject data are required.', '/');
        }

        $stmt = Database::getInstance()->prepare(
            'SELECT u.id, u.username, u.public_key, h.full_name, h.id_number
               FROM users u JOIN holders h ON h.user_id = u.id
              WHERE u.id = :id LIMIT 1'
        );
        $stmt->execute([':id' => $holderId]);
        $holder = $stmt->fetch();
        if (!$holder) $this->flashAndRedirect('error', 'Holder not found.', '/');

        $stmt = Database::getInstance()->prepare(
            'SELECT u.username, u.public_key, u.did, i.organisation
               FROM users u JOIN issuers i ON i.user_id = u.id
              WHERE u.id = :id LIMIT 1'
        );
        $stmt->execute([':id' => $this->authUserId()]);
        $issuer = $stmt->fetch();
        if (!$issuer) $this->flashAndRedirect('error', 'Issuer profile not found.', '/');

        $subjectJson = json_decode($subjectData, true);
        if (!is_array($subjectJson)) $subjectJson = ['description' => $subjectData];

        // ── AUTO-GENERATE the numeric Certificate Serial Number ──────────────
        // This is generated by the SYSTEM at issuance time — the issuer never
        // types it manually. Guaranteed unique against the credentials table.
        $certificateSerial = $this->generateCertificateSerial();

        // Inject the serial into the credential subject so it is part of the
        // signed payload (tamper-evident) and visible in the JSON-LD.
        $subjectJson['certificateSerial'] = $certificateSerial;

        $credentialId = 'urn:uuid:' . $this->generateUuid();
        $issuedAt     = date('c');
        $issuerDid    = $issuer['did'] ?? ('did:kazsign:' . hash('sha256', $issuer['username']));
        $holderDid    = 'did:kazsign:' . hash('sha256', $holder['username']);

        $credential = [
            '@context' => [
                'https://www.w3.org/2018/credentials/v1',
                'https://www.w3.org/2018/credentials/examples/v1',
            ],
            'id'   => $credentialId,
            'type' => ['VerifiableCredential', $credentialType],
            'issuer' => [
                'id'        => $issuerDid,
                'name'      => $issuer['organisation'],
                'publicKey' => $issuer['public_key'],
            ],
            'issuanceDate'      => $issuedAt,
            'credentialSubject' => array_merge([
                'id'                => $holderDid,
                'name'              => $holder['full_name'],
                'idNumber'          => $holder['id_number'],
                'certificateSerial' => $certificateSerial,
            ], $subjectJson),
        ];

        $jsonld   = json_encode($credential, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $fileHash = hash('sha256', $jsonld);

        $privateKey = $_SESSION['private_key'] ?? null;
        if ($privateKey === null) {
            $this->flashAndRedirect('error', 'No private key in session. Re-login with your key.', '/');
        }

        try {
            $engine    = new KazSignEngine();
            $signature = $engine->signData($jsonld, $privateKey);
        } catch (\Throwable $e) {
            error_log('[KazSign] Signing failed: ' . $e->getMessage());
            $this->flashAndRedirect('error', 'Signing failed. Check server logs.', '/');
        }

        $credential['proof'] = [
            'type'               => 'KazSignPQC2024',
            'algorithm'          => 'KAZ-SIGN-128 (Post-Quantum)',
            'created'            => $issuedAt,
            'verificationMethod' => $issuerDid . '#key-1',
            'proofValue'         => $signature,
        ];

        $signedJsonld = json_encode($credential, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        try {
            $stmt = Database::getInstance()->prepare(
                'INSERT INTO credentials
                    (issuer_id, holder_id, credential_id, subject, jsonld, signature, file_hash, status)
                 VALUES
                    (:issuer_id, :holder_id, :credential_id, :subject, :jsonld, :signature, :file_hash, :status)'
            );
            $stmt->execute([
                ':issuer_id'     => $this->authUserId(),
                ':holder_id'     => $holderId,
                ':credential_id' => $credentialId,
                ':subject'       => json_encode($subjectJson),
                ':jsonld'        => $signedJsonld,
                ':signature'     => $signature,
                ':file_hash'     => $fileHash,
                ':status'        => 'issued',
            ]);
        } catch (\Throwable $e) {
            error_log('[KazSign] Credential DB insert failed: ' . $e->getMessage());
            $this->flashAndRedirect('error', 'Database error: ' . $e->getMessage(), '/');
        }

        $this->flashAndRedirect(
            'success',
            "Credential issued to {$holder['full_name']} successfully. " .
            "Certificate Serial No: <strong>{$certificateSerial}</strong>",
            '/'
        );
    }

    // =========================================================================
    //  POST /credentials/revoke  (Issuer only)
    // =========================================================================

    public function revoke(array $params = []): void
    {
        $this->requireAuth();
        $this->requireRole('issuer');
        $this->validateCsrf();

        $credentialDbId = (int) ($_POST['credential_db_id'] ?? 0);

        if ($credentialDbId === 0) {
            $this->flashAndRedirect('error', 'Invalid credential.', '/');
        }

        $stmt = Database::getInstance()->prepare(
            'SELECT id, status, issuer_id FROM credentials WHERE id = :id LIMIT 1'
        );
        $stmt->execute([':id' => $credentialDbId]);
        $cred = $stmt->fetch();

        if (!$cred) {
            $this->flashAndRedirect('error', 'Credential not found.', '/');
        }

        if ((int)$cred['issuer_id'] !== $this->authUserId()) {
            $this->flashAndRedirect('error', 'You can only revoke credentials you issued.', '/');
        }

        if ($cred['status'] === 'revoked') {
            $this->flashAndRedirect('error', 'This credential is already revoked.', '/');
        }

        $stmt = Database::getInstance()->prepare(
            'UPDATE credentials SET status = :status WHERE id = :id'
        );
        $stmt->execute([':status' => 'revoked', ':id' => $credentialDbId]);

        $this->flashAndRedirect('success', 'Credential has been revoked successfully.', '/');
    }

    // =========================================================================
    //  POST /credentials/verify  (Verifier only)
    //  Looks up the credential by its CERTIFICATE SERIAL NUMBER.
    // =========================================================================

    public function verify(array $params = []): void
    {
        $this->requireAuth();
        $this->requireRole('verifier');
        $this->validateCsrf();

        // Accept the new field name; fall back to old one for compatibility.
        $certificateSerial = trim(
            $_POST['certificate_serial'] ?? ($_POST['credential_id'] ?? '')
        );

        if ($certificateSerial === '') {
            $this->flashAndRedirect('error', 'Please enter a Certificate Serial Number.', '/');
        }

        // ── STEP 1: Find the credential by certificate serial ─────────────────
        // The serial lives inside the JSON-LD credentialSubject. We match it
        // against the stored `subject` JSON (and `jsonld` as a safety net),
        // then pull issuer DID in the same pass.
        $stmt = Database::getInstance()->prepare(
            'SELECT c.*, u.did AS issuer_did
               FROM credentials c
               JOIN users u ON u.id = c.issuer_id'
        );
        $stmt->execute();
        $allRows = $stmt->fetchAll() ?: [];

        $cred = null;
        foreach ($allRows as $row) {
            $serialInRow = $this->extractCertificateSerial($row);
            if ($serialInRow !== null && $serialInRow === $certificateSerial) {
                $cred = $row;
                break;
            }
        }

        if (!$cred) {
            $this->renderVerifierDashboard(
                ['type' => 'error', 'message' => 'Certificate Serial Number not found in the system.'],
                null
            );
            return;
        }

        // ── STEP 2: Resolve issuer public key from trust registry ─────────────
        $regStmt = Database::getInstance()->prepare(
            'SELECT public_key, status FROM trust_registry
              WHERE did = :did LIMIT 1'
        );
        $regStmt->execute([':did' => $cred['issuer_did']]);
        $registryEntry = $regStmt->fetch();

        if (!$registryEntry) {
            // Fallback: try to get public key directly from users table
            $fallbackStmt = Database::getInstance()->prepare(
                'SELECT public_key FROM users WHERE id = :id LIMIT 1'
            );
            $fallbackStmt->execute([':id' => $cred['issuer_id']]);
            $fallbackUser = $fallbackStmt->fetch();

            if (!$fallbackUser || empty($fallbackUser['public_key'])) {
                $this->renderVerifierDashboard(
                    ['type' => 'error', 'message' => '✗ Issuer not found in trust registry and public key unavailable.'],
                    null
                );
                return;
            }

            $issuerPublicKey = $fallbackUser['public_key'];
        } elseif ($registryEntry['status'] !== 'active') {
            $this->renderVerifierDashboard(
                ['type' => 'error', 'message' => '✗ The issuer of this credential is no longer a trusted issuer.'],
                null
            );
            return;
        } else {
            $issuerPublicKey = $registryEntry['public_key'];
        }

        // ── STEP 3: Check for revocation before cryptographic verification ────
        if ($cred['status'] === 'revoked') {
            $this->renderVerifierDashboard(
                ['type' => 'error', 'message' => 'This credential has been REVOKED by the issuer and is no longer valid.'],
                [
                    'credential'      => $cred,
                    'jsonld'          => json_decode($cred['jsonld'], true),
                    'hash_intact'     => false,
                    'signature_valid' => false,
                    'verified'        => false,
                    'revoked'         => true,
                ]
            );
            return;
        }

        // ── STEP 4: Two-layer verification ────────────────────────────────────

        // Layer 1: SHA-256 hash integrity
        $jsonldData = json_decode($cred['jsonld'], true);
        unset($jsonldData['proof']);
        $jsonldNoProof = json_encode($jsonldData, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $computedHash  = hash('sha256', $jsonldNoProof);
        $hashIntact    = hash_equals($cred['file_hash'], $computedHash);

        // Layer 2: KAZ-SIGN-128 digital signature
        $engine         = new KazSignEngine();
        $signatureValid = $engine->verifySignature(
            $jsonldNoProof,
            $cred['signature'],
            $issuerPublicKey
        );

        $verified  = $hashIntact && $signatureValid;
        $newStatus = $verified ? 'verified' : 'rejected';

        // ── STEP 5: Update credential status ──────────────────────────────────
        $stmt = Database::getInstance()->prepare(
            'UPDATE credentials SET status = :status WHERE id = :id'
        );
        $stmt->execute([':status' => $newStatus, ':id' => $cred['id']]);
        $cred['status'] = $newStatus;

        $this->renderVerifierDashboard(
            [
                'type'    => $verified ? 'success' : 'error',
                'message' => $verified
                    ? '✓ Credential is authentic and untampered.'
                    : '✗ Verification FAILED — signature invalid or credential was modified.',
            ],
            [
                'credential'      => $cred,
                'jsonld'          => json_decode($cred['jsonld'], true),
                'hash_intact'     => $hashIntact,
                'signature_valid' => $signatureValid,
                'verified'        => $verified,
                'revoked'         => false,
            ]
        );
    }

    // =========================================================================
    //  GET /credentials/:id/show
    // =========================================================================

    public function show(array $params = []): void
    {
        $this->requireAuth();

        $id   = (int) ($params['id'] ?? 0);
        $stmt = Database::getInstance()->prepare(
            'SELECT * FROM credentials WHERE id = :id LIMIT 1'
        );
        $stmt->execute([':id' => $id]);
        $cred = $stmt->fetch();

        if (!$cred) $this->flashAndRedirect('error', 'Credential not found.', '/');

        $userId = $this->authUserId();
        if ((int)$cred['holder_id'] !== $userId && (int)$cred['issuer_id'] !== $userId) {
            $this->flashAndRedirect('error', 'Access denied.', '/');
        }

        $this->render('dashboard', [
            'credentials'    => [$cred],
            'holders'        => [],
            'issuer_profile' => [],
            'flash'          => $this->consumeFlash(),
            'csrf_token'     => $this->generateCsrfToken(),
            'result'         => null,
        ]);
    }

    // =========================================================================
    //  Helpers
    // =========================================================================

    private function renderVerifierDashboard(?array $flash, ?array $result): void
    {
        $this->render('dashboard', [
            'credentials'    => [],
            'holders'        => [],
            'issuer_profile' => [],
            'flash'          => $flash,
            'csrf_token'     => $this->generateCsrfToken(),
            'result'         => $result,
        ]);
    }

    private function requireRole(string $role): void
    {
        if (($_SESSION['role'] ?? '') !== $role) {
            $this->flashAndRedirect('error', "Access denied. This action is for {$role}s only.", '/');
        }
    }

    /**
     * Generate a unique numeric certificate serial number.
     *
     * Format: a random 8-digit number   e.g. 88903405
     *
     * Re-rolls with a fresh random number on the rare chance of a collision
     * against an existing credential's stored serial.
     */
    private function generateCertificateSerial(): string
    {
        // Random 8-digit number, re-rolled until unique.
        for ($attempt = 0; $attempt < 30; $attempt++) {
            $serial = (string) random_int(10000000, 99999999);
            if (!$this->serialExists($serial)) {
                return $serial;
            }
        }

        // Extremely unlikely final fallback.
        return (string) random_int(10000000, 99999999);
    }

    /**
     * Check whether a certificate serial already exists in any stored credential.
     */
    private function serialExists(string $serial): bool
    {
        try {
            $stmt = Database::getInstance()->prepare('SELECT subject, jsonld FROM credentials');
            $stmt->execute();
            foreach (($stmt->fetchAll() ?: []) as $row) {
                $existing = $this->extractCertificateSerial($row);
                if ($existing !== null && $existing === $serial) {
                    return true;
                }
            }
        } catch (\Throwable $e) {
            error_log('[KazSign] serialExists check failed: ' . $e->getMessage());
        }
        return false;
    }

    /**
     * Pull the certificateSerial out of a credentials-table row.
     * Checks the `subject` JSON first, then falls back to `jsonld`.
     */
    private function extractCertificateSerial(array $row): ?string
    {
        // Prefer the compact `subject` column.
        if (!empty($row['subject'])) {
            $subj = json_decode($row['subject'], true);
            if (is_array($subj) && !empty($subj['certificateSerial'])) {
                return (string) $subj['certificateSerial'];
            }
        }

        // Fall back to the full signed JSON-LD.
        if (!empty($row['jsonld'])) {
            $jld = json_decode($row['jsonld'], true);
            if (is_array($jld)
                && isset($jld['credentialSubject']['certificateSerial'])
            ) {
                return (string) $jld['credentialSubject']['certificateSerial'];
            }
        }

        return null;
    }

    private function generateUuid(): string
    {
        $data    = random_bytes(16);
        $data[6] = chr(ord($data[6]) & 0x0f | 0x40);
        $data[8] = chr(ord($data[8]) & 0x3f | 0x80);
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }

    private function validateCsrf(): void
    {
        $posted  = $_POST['csrf_token'] ?? '';
        $session = $_SESSION['csrf_token'] ?? '';
        if (!hash_equals($session, $posted)) {
            http_response_code(403);
            exit('Invalid CSRF token.');
        }
    }

    private function flashAndRedirect(string $type, string $message, string $url): never
    {
        $_SESSION['flash'] = ['type' => $type, 'message' => $message];
        $this->redirect($url);
    }

    private function consumeFlash(): ?array
    {
        if (!isset($_SESSION['flash'])) return null;
        $flash = $_SESSION['flash'];
        unset($_SESSION['flash']);
        return $flash;
    }

    private function generateCsrfToken(): string
    {
        if (empty($_SESSION['csrf_token'])) {
            $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
        }
        return $_SESSION['csrf_token'];
    }
}